# Generated by Django 4.0.2 on 2022-02-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remain',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remains', to='retail_app.store'),
        ),
    ]
