# Generated by Django 4.0.2 on 2022-02-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0002_alter_remain_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='products',
            new_name='product',
        ),
    ]
