# Generated by Django 4.0.2 on 2022-02-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0003_rename_products_store_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='retail_app.product'),
        ),
        migrations.RemoveField(
            model_name='supply',
            name='product',
        ),
        migrations.AddField(
            model_name='supply',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='retail_app.product'),
            preserve_default=False,
        ),
    ]
